from tqdm import tqdm
import torch
import faiss
import numpy as np
from model.extract_feature import get_embeddings

def build_retriever_save(model, device, test_dataloader, index_path, labels_path):
    """
    Builds a FAISS index from image embeddings generated by the given model and saves both the index and corresponding labels to disk.

    Args:
        model (torch.nn.Module): The model used to generate image embeddings.
        device (torch.device): The device (CPU or CUDA) to perform computations on.
        test_dataloader (torch.utils.data.DataLoader): DataLoader providing batches of images, masks, and labels.
        index_path (str or Path): File path to save the FAISS index.
        labels_path (str or Path): File path to save the labels as a NumPy array.

    Returns:
        tuple: A tuple containing:
            - index (faiss.IndexFlatIP): The built FAISS index containing all image embeddings.
            - all_labels (list): List of all labels corresponding to the embeddings.

    Usage:
        >>> index, labels = build_retriever_save(model, device, dataloader, "index.faiss", "labels.npy")
        # This will save the FAISS index to 'index.faiss' and the labels to 'labels.npy'.
    """
    d = model.config.hidden_size
    index = faiss.IndexFlatIP(d)

    all_labels=[]
    with torch.no_grad():
        for images, masks, labels in tqdm(test_dataloader, desc="building bank"):
            images = images.to(device)
            image_tensor = get_embeddings(model, device,masks, images)
            all_labels.extend(labels)
            index.add(image_tensor.cpu().numpy())

    faiss.write_index(index, str(index_path))
    np.save(str(labels_path), all_labels)

    torch.cuda.empty_cache()
    print(f"FAISS index and labels saved to {index_path} and {labels_path}.")

    return index,all_labels

def search_retriever(index, query):
    D, I = index.search(query, 11)  # 检索前 10 个邻居
    return D[0], I[0]